### ISSUE TITLE
Add compilation instruction to README and example config.

### ISSUE THREAD

**Issue by ahmadraniri1994** [DeedleFake/kawa#4]
Hello, It's interesting to find your project. I think it will be great if the compilation instruction is added into README file. Just an advice, oh also example configuration will be great too.

**Comment by DeedleFake** [comment]
Good idea. Compilation's not too complicated, as it's a normal Go module, but it, or, more precisely, `deedles.dev/wlr`, does have some C dependencies that will need to be installed. It also uses a vanity URL for the module, which might not be as obvious as it could be.

There is no configuration at the moment as the project is still in heavy development and not at all ready for regular usage, though basic usage might not be too far off now.

I should also add a warning noting that there's something wrong with the initialization that causes it to completely lock up all input on the machine if run in a TTY. It works fine with the Wayland backend, though.

**Comment by DeedleFake** [comment]
Closed by 21afeb5.
